"""添加菜谱图片字段和原料可选字段

Revision ID: 20260304_add_recipe_images
Revises:
Create Date: 2026-03-04 22:06:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite, postgresql, mysql

# revision identifiers, used by Alembic.
revision = '20260304_add_recipe_images'
down_revision = None  # 首个迁移
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    # 添加 recipes 表的 images 字段
    op.add_column('recipes', sa.Column('images', sa.JSON(), nullable=True, server_default='[]'))

    # 添加 recipe_ingredients 表的新字段（使用 JSON 类型）
    op.add_column('recipe_ingredients', sa.Column('quantity_range', sa.JSON(), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('is_optional', sa.Boolean(), nullable=True, server_default='0'))
    op.add_column('recipe_ingredients', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('original_quantity', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    # 删除添加的字段
    op.drop_column('recipe_ingredients', 'original_quantity')
    op.drop_column('recipe_ingredients', 'note')
    op.drop_column('recipe_ingredients', 'is_optional')
    op.drop_column('recipe_ingredients', 'quantity_range')
    op.drop_column('recipes', 'images')
    # ### end Alembic commands ###
