"""refactor product_ingredient_links

Revision ID: b60666838e2d
Revises: make_product_id_not_null
Create Date: 2026-03-05 19:20:56.457600+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60666838e2d'
down_revision: Union[str, None] = 'make_product_id_not_null'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_ingredient_links', sa.Column('product_id', sa.Integer(), nullable=False))
    op.alter_column('product_ingredient_links', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'product_ingredient_links', type_='foreignkey')
    op.create_foreign_key(None, 'product_ingredient_links', 'products', ['product_id'], ['id'])
    op.drop_column('product_ingredient_links', 'product_record_id')
    op.drop_column('product_ingredient_links', 'match_method')
    op.drop_column('product_ingredient_links', 'verification_notes')
    op.drop_column('product_ingredient_links', 'verified_by_user')
    op.drop_column('product_ingredient_links', 'match_confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_ingredient_links', sa.Column('match_confidence', sa.NUMERIC(precision=3, scale=2), nullable=True))
    op.add_column('product_ingredient_links', sa.Column('verified_by_user', sa.BOOLEAN(), nullable=True))
    op.add_column('product_ingredient_links', sa.Column('verification_notes', sa.VARCHAR(length=500), nullable=True))
    op.add_column('product_ingredient_links', sa.Column('match_method', sa.VARCHAR(length=50), nullable=True))
    op.add_column('product_ingredient_links', sa.Column('product_record_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'product_ingredient_links', type_='foreignkey')
    op.create_foreign_key(None, 'product_ingredient_links', 'product_records', ['product_record_id'], ['id'])
    op.alter_column('product_ingredient_links', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('product_ingredient_links', 'product_id')
    # ### end Alembic commands ###
