"""recipe: 让 Recipe 继承 AuditMixin

Revision ID: 32de12f1b4d9
Revises: b5b7972ffad9
Create Date: 2026-03-05 19:04:17.234443+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32de12f1b4d9'
down_revision: Union[str, None] = 'b5b7972ffad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite 不支持直接添加列和外键约束，需要使用 batch 模式重建表
    with op.batch_alter_table('recipes', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('created_at', nullable=False)
        batch_op.create_foreign_key('fk_recipes_created_by', 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_recipes_updated_by', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite 不支持直接删除列和外键约束，需要使用 batch 模式重建表
    with op.batch_alter_table('recipes', recreate='always') as batch_op:
        batch_op.drop_constraint('fk_recipes_created_by', type_='foreignkey')
        batch_op.drop_constraint('fk_recipes_updated_by', type_='foreignkey')
        batch_op.alter_column('created_at', nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
    # ### end Alembic commands ###
