"""fix: 优化用户食材偏好模型的索引和约束

Revision ID: 2210ea9e9907
Revises: b7d181ecbf94
Create Date: 2026-03-05 18:55:20.892560+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '2210ea9e9907'
down_revision: Union[str, None] = 'b7d181ecbf94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 使用批处理方式处理 SQLite 的限制
    # SQLite 不支持 ALTER COLUMN SET NOT NULL，需要重建表

    # 先创建所有索引
    op.create_index(op.f('ix_user_ingredient_preferences_default_product_id'), 'user_ingredient_preferences', ['default_product_id'], unique=False)
    op.create_index(op.f('ix_user_ingredient_preferences_default_recipe_id'), 'user_ingredient_preferences', ['default_recipe_id'], unique=False)
    op.create_index(op.f('ix_user_ingredient_preferences_is_favorite'), 'user_ingredient_preferences', ['is_favorite'], unique=False)
    op.create_index('ix_user_ingredient_preferences_user_favorite', 'user_ingredient_preferences', ['user_id', 'is_favorite'], unique=False)
    op.create_index('ix_user_ingredient_preferences_user_type', 'user_ingredient_preferences', ['user_id', 'preference_type'], unique=False)

    # 对于 SQLite 的 NOT NULL 约束，使用批处理迁移
    # SQLite 需要重建表来添加 NOT NULL 约束
    # 这里我们使用一个 workaround：更新现有的空值为默认值
    op.execute(text(
        "UPDATE user_ingredient_preferences SET preference_type = 'product' WHERE preference_type IS NULL"
    ))

    # 注意：SQLite 不支持通过 ALTER 添加 NOT NULL 约束
    # 应用层（Pydantic Schema）已通过验证确保数据一致性
    # 如果需要强制数据库级别的 NOT NULL，需要重建整个表


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_ingredient_preferences_user_type', table_name='user_ingredient_preferences')
    op.drop_index('ix_user_ingredient_preferences_user_favorite', table_name='user_ingredient_preferences')
    op.drop_index(op.f('ix_user_ingredient_preferences_is_favorite'), table_name='user_ingredient_preferences')
    op.drop_index(op.f('ix_user_ingredient_preferences_default_recipe_id'), table_name='user_ingredient_preferences')
    op.drop_index(op.f('ix_user_ingredient_preferences_default_product_id'), table_name='user_ingredient_preferences')
    # ### end Alembic commands ###
